### ISSUE TITLE
Platform error tts.reversotts - No module named 'pyttsreverso'

### ISSUE THREAD

**Issue by ishalem** [rt400/ReversoTTS-HA#1]
I get this message after following the installation guide

**Comment by tal2420** [comment]
Same here

**Comment by rt400** [comment]
which version of HA you used ?

**Comment by ishalem** [comment]
I don't remember the version I used when opened this issue but usually, I'm on the latest 0.115.4 and get the following:

Logger: homeassistant.components.websocket_api.http.connection.140002793230448
Source: components/tts/__init__.py:471
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:57:10 PM (1 occurrences)
Last logged: 12:57:10 PM

Invalid MultiSpec data: TextFrame(encoding=<Encoding.UTF8: 3>, text=['he-IL-Asaf-Hebrew'])
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/mutagen/easyid3.py", line 124, in setter
    frame = id3[frameid]
  File "/usr/local/lib/python3.8/site-packages/mutagen/_util.py", line 537, in __getitem__
    return self.__dict[key]
KeyError: 'TPE1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1315, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1350, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 168, in async_say_handle
    url = await tts.async_get_url(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 341, in async_get_url
    filename = await self.async_get_tts_audio(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 368, in async_get_tts_audio
    data = self.write_tags(filename, data, provider, message, language, options)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 471, in write_tags
    tts_file["artist"] = ID3Text(encoding=3, text=artist)
  File "/usr/local/lib/python3.8/site-packages/mutagen/_file.py", line 74, in __setitem__
    self.tags[key] = value
  File "/usr/local/lib/python3.8/site-packages/mutagen/easyid3.py", line 222, in __setitem__
    return func(self.__id3, key, value)
  File "/usr/local/lib/python3.8/site-packages/mutagen/easyid3.py", line 126, in setter
    id3.add(mutagen.id3.Frames[frameid](encoding=3, text=value))
  File "/usr/local/lib/python3.8/site-packages/mutagen/id3/_frames.py", line 65, in __init__
    setattr(self, checker.name,
  File "/usr/local/lib/python3.8/site-packages/mutagen/id3/_frames.py", line 76, in __setattr__
    self._setattr(name, checker.validate(self, value))
  File "/usr/local/lib/python3.8/site-packages/mutagen/id3/_specs.py", line 533, in validate
    raise ValueError('Invalid MultiSpec data: %r' % value)
ValueError: Invalid MultiSpec data: TextFrame(encoding=<Encoding.UTF8: 3>, text=['he-IL-Asaf-Hebrew'])

**Comment by rt400** [comment]
Please send the Core of HomeAssistant (HASS or DOCKER ...).
If you can upload your settings for TTS, cause in your log that you submitted has no mention of the dependency issue.
For me in HA (DOCKER) it works fine and it depends on pyttsreverso.
And did you copy exactly all the files as listed in my explanation?

**Comment by ishalem** [comment]
Sure.
I use homeassistant on docker running in ubuntu NUC

**configuration:**


![image](https://user-images.githubusercontent.com/3824532/94809913-fc547480-03fb-11eb-9f6a-79c21e9ee629.png)


**Files**:

![image](https://user-images.githubusercontent.com/3824532/94809755-bc8d8d00-03fb-11eb-9bc1-085b43dba4e6.png)

**Comment by rt400** [comment]
thanks, its looks like a bug in HA on google translate.
you can see [here](https://community.home-assistant.io/t/0-115-b-day-release-media-browser-tags-automations-wth/227518/641)
Has nothing to do with my component.
We have to wait for a solution from HA.
I close this issue...

**Comment by ishalem** [comment]
so if ill keep only the reversto configuration under tts it will work?

**Comment by krue81** [comment]
I'm getting the same error:

Configuration invalid
Platform error tts.reversotts - No module named 'pyttsreverso'

And I don't have Google TTS configured in configuration.yaml:

# Text to speech
tts:
  - platform: reversotts
    language: 'Ines-Spanish'
    pitch: "100"
    bitrate: "128k"

**Comment by rt400** [comment]
@krue81 How did you install this components ? and what Core of HA your are using (Docker,Hass,...)?

**Comment by fyford** [comment]
I have this issue on HASS  after the latest update, looks like it might be a HACS issue... not managed to figure it out yet
